build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  variables:
    IMAGE: registry.gitlab.com/qrinef/crm-frontend-nuxt
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    - docker build -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE
