version: "3"

services:
  app:
    image: registry.gitlab.com/qrinef/crm-backend-nest:latest
    container_name: crm-backend-nest
    expose:
      - 3010
    environment:
      VIRTUAL_HOST: crm-backend-nest.qrinef.ru
      VIRTUAL_PORT: 3010

  db:
    image: postgres:12-alpine
    container_name: db
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432

networks:
  default:
    external:
      name: nginx-proxy
