version: "3"

services:
  app:
    image: registry.gitlab.com/qrinef/crm-backend-nest:latest
    container_name: crm-backend-nest
    expose:
      - 3010
    environment:
      VIRTUAL_HOST: crm-backend-nest.qrinef.ru
      VIRTUAL_PORT: 3010

networks:
  default:
    external:
      name: nginx-proxy
