version: '3.7'

services:
  app:
    build:
      context: .
      target: development
    container_name: app
    depends_on:
      - db
    volumes:
      - ./src:/app/src
    ports:
      - 3010:3010
    command: npm run start:dev

  db:
    image: postgres:12-alpine
    container_name: db
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432