version: '3.7'

services:
  app:
    image: docker.pkg.github.com/qrinef/crm-backend-nest/crm-backend-nest:latest
    container_name: app
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    expose:
      - 3010
    environment:
      VIRTUAL_HOST: crm-backend-nest.qrinef.ru
      VIRTUAL_PORT: 3010

  db:
    image: postgres:12-alpine
    container_name: db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - 5432:5432

networks:
  default:
    external:
      name: nginx-proxy
